server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testactiviti?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://localhost:27017/zhanglingfei

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity